import React from 'react';
import { format } from 'date-fns';

interface TaxReceiptProps {
    record: any;
    settings: any;
}

export const TaxReceipt = React.forwardRef<HTMLDivElement, TaxReceiptProps>(({ record, settings }, ref) => {
    if (!record) return null;

    return (
        <div ref={ref} className="p-8 bg-white text-black" style={{ width: '210mm', minHeight: '140mm', margin: '0 auto' }}>
            {/* Header */}
            <div className="text-center border-b-2 border-dashed border-gray-300 pb-4 mb-6">
                <h1 className="text-2xl font-bold uppercase">{settings?.siteName || 'Union Parishad'}</h1>
                <p className="text-sm text-gray-600">{settings?.unionAddressBn || 'Union Parishad Address'}</p>
                <div className="mt-2 inline-block px-3 py-1 bg-gray-100 rounded text-sm font-semibold border border-gray-300">
                    HOLDING TAX RECEIPT
                </div>
            </div>

            {/* Receipt Info */}
            <div className="flex justify-between items-start mb-6 text-sm">
                <div>
                    <p className="mb-1"><span className="font-semibold">Receipt No:</span> {record.receiptNumber}</p>
                    <p><span className="font-semibold">Date:</span> {format(new Date(record.paidAt), 'dd MMM yyyy, hh:mm a')}</p>
                </div>
                <div className="text-right">
                    <p className="mb-1"><span className="font-semibold">Financial Year:</span> {record.financialYear}</p>
                </div>
            </div>

            {/* Citizen Info */}
            <div className="mb-6 p-4 border rounded-lg bg-gray-50 text-sm">
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <p className="text-gray-500 text-xs uppercase">Citizen Name</p>
                        <p className="font-semibold text-lg">{record.citizenId?.name || 'N/A'}</p>
                    </div>
                    <div>
                        <p className="text-gray-500 text-xs uppercase">National ID (NID)</p>
                        <p className="font-semibold">{record.citizenId?.nid || 'N/A'}</p>
                    </div>
                    <div>
                        <p className="text-gray-500 text-xs uppercase">Father's Name</p>
                        <p>{record.citizenId?.fatherName || 'N/A'}</p>
                    </div>
                    <div>
                        <p className="text-gray-500 text-xs uppercase">Village</p>
                        <p>{record.citizenId?.village || 'N/A'}</p>
                    </div>
                </div>
            </div>

            {/* Payment Details */}
            <div className="mb-12">
                <table className="w-full text-sm border-collapse">
                    <thead>
                        <tr className="bg-gray-100 border-y border-gray-300">
                            <th className="py-2 text-left pl-4">Description</th>
                            <th className="py-2 text-right pr-4">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr className="border-b border-gray-200">
                            <td className="py-3 pl-4">Holding Tax ({record.financialYear})</td>
                            <td className="py-3 text-right pr-4 font-mono">৳{record.amount}</td>
                        </tr>
                        <tr>
                            <td className="py-3 pl-4 font-bold">Total Paid</td>
                            <td className="py-3 text-right pr-4 font-bold text-lg font-mono">৳{record.amount}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {/* Footer */}
            <div className="flex justify-between items-end mt-20 pt-4">
                <div className="text-center">
                    <div className="w-32 border-t border-gray-400 mb-1"></div>
                    <p className="text-xs text-gray-500">Collected By</p>
                </div>
                <div className="text-center">
                    <div className="w-32 border-t border-gray-400 mb-1"></div>
                    <p className="text-xs text-gray-500">Authorized Signature</p>
                </div>
            </div>

            <div className="mt-8 text-center text-[10px] text-gray-400">
                Generated by {settings?.siteName || 'Union Admin System'} on {format(new Date(), 'dd MMM yyyy')}
            </div>
        </div>
    );
});

TaxReceipt.displayName = 'TaxReceipt';
